name: diffnets-test-conda
channels:
  - conda-forge
  - defaults
  - anaconda
dependencies:
  - python=3.7
  - pip
  - git
  - sphinx_rtd_theme
  - sphinx
  - mdtraj
  - pytorch
  - torchvision
  - click
  - scikit-learn
  - matplotlib
  - cython
  - mpi4py
  - pytest
  - pytest-cov
  - pyyaml
   
  - pip:
    - git+git://github.com/bowman-lab/enspara
